apiVersion: v1
kind: Service
metadata:
  labels:
      app: nginx
  name: nginx
  namespce: argocd-test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
     app: nginx
  type: NodePort
